DROP TABLE IF EXISTS  voter_playlists CASCADE;

CREATE TABLE voter_playlists (
id SERIAL PRIMARY KEY NOT NULL,
user_id VARCHAR(255) NOT NULL,
playlist_id INTEGER REFERENCES playlists(id) ON DELETE CASCADE
);

