DROP TABLE IF EXISTS  voter_playlist CASCADE;

CREATE TABLE voter_playlist (
id SERIAL PRIMARY KEY NOT NULL,
user_id VARCHAR(255) NOT NULL,
playlist_id INTEGER REFERENCES playlist(id) ON DELETE CASCADE
);

